#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d    󰨞 

bspc config window_gap          12

bspc config border_width        4
bspc config focused_border_color "#89b4fa"
bspc config normal_border_color "#666"

bspc config border_radius	5
bspc config top_padding 	20
bspc config right_padding	3
bspc config left_padding	3
bspc config side_padding	3
bspc config split_ratio          1.0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config border_radius 		 6
bspc config pointer_modifier	mod1
bspc config swallow_first_click true


bspc rule -a Chromium desktop='^1'
bspc rule -a kitty desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a sublime_text desktop='^4'
bspc rule -a Deadbeef desktop='^5'
bspc rule -a mpv desktop='^6'
bspc rule -a Ripcord desktop='^7'
bspc rule -a Spotify desktop='^8'


bspc rule -a Zathura state=tiled

dunst &
nm-applet &
mpd &
nitrogen --restore &
emote &
picom  --config ~/.config/picom/new.conf &
exec ~/.config/polybar/launch.sh --forest &
